name: clikr-server
channels:
  - defaults
dependencies:
  - python=3.7.2
  - pip=19.1.1
  pip:
    - flask_script
    - flask_migrate
    - flask_cors
    - flask_socketio
    - flask_sslify
    - marshmallow
    - psycopg2