"""empty message

Revision ID: 02082b0d5aa2
Revises: b4e5eabc17f1
Create Date: 2020-08-23 16:48:24.757648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02082b0d5aa2'
down_revision = 'b4e5eabc17f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professors', sa.Column('password_hash', sa.String(length=256), nullable=False))
    op.add_column('professors', sa.Column('salt', sa.String(length=128), nullable=False))
    op.create_unique_constraint(None, 'professors', ['salt'])
    op.create_unique_constraint(None, 'professors', ['password_hash'])
    op.add_column('students', sa.Column('password_hash', sa.String(length=256), nullable=False))
    op.add_column('students', sa.Column('salt', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'salt')
    op.drop_column('students', 'password_hash')
    op.drop_constraint(None, 'professors', type_='unique')
    op.drop_constraint(None, 'professors', type_='unique')
    op.drop_column('professors', 'salt')
    op.drop_column('professors', 'password_hash')
    # ### end Alembic commands ###
