"""empty message

Revision ID: 2f6effab87b6
Revises: 3a82a270ce6e
Create Date: 2018-11-02 12:04:11.839334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f6effab87b6'
down_revision = '3a82a270ce6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lecture_id', sa.String(length=36), nullable=True),
    sa.Column('question_type', sa.String(length=32), nullable=False),
    sa.Column('question_title', sa.String(length=256), nullable=True),
    sa.Column('question_text', sa.String(length=1024), nullable=True),
    sa.Column('creator_id', sa.String(length=36), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['professors.id'], ),
    sa.ForeignKeyConstraint(['lecture_id'], ['lectures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    # ### end Alembic commands ###
