"""added drag-and-drop model

Revision ID: 39b79b8eee47
Revises: 69cd3950245b
Create Date: 2018-12-15 20:06:55.777153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39b79b8eee47'
down_revision = '69cd3950245b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('answer1', sa.String(length=1024), nullable=True))
    op.add_column('questions', sa.Column('answer2', sa.String(length=1024), nullable=True))
    op.add_column('questions', sa.Column('answer3', sa.String(length=1024), nullable=True))
    op.add_column('questions', sa.Column('answer4', sa.String(length=1024), nullable=True))
    op.add_column('questions', sa.Column('answer5', sa.String(length=1024), nullable=True))
    op.add_column('questions', sa.Column('number_of_questions', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('question1', sa.String(length=1024), nullable=True))
    op.add_column('questions', sa.Column('question2', sa.String(length=1024), nullable=True))
    op.add_column('questions', sa.Column('question3', sa.String(length=1024), nullable=True))
    op.add_column('questions', sa.Column('question4', sa.String(length=1024), nullable=True))
    op.add_column('questions', sa.Column('question5', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'question5')
    op.drop_column('questions', 'question4')
    op.drop_column('questions', 'question3')
    op.drop_column('questions', 'question2')
    op.drop_column('questions', 'question1')
    op.drop_column('questions', 'number_of_questions')
    op.drop_column('questions', 'answer5')
    op.drop_column('questions', 'answer4')
    op.drop_column('questions', 'answer3')
    op.drop_column('questions', 'answer2')
    op.drop_column('questions', 'answer1')
    # ### end Alembic commands ###
