"""empty message

Revision ID: 647d7b9c0107
Revises: a22ca99c5c13
Create Date: 2018-11-02 18:09:03.420480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '647d7b9c0107'
down_revision = 'a22ca99c5c13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'number_of_options',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'number_of_options',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
