"""empty message

Revision ID: 830c991058e4
Revises: 647d7b9c0107
Create Date: 2018-11-05 17:45:51.655073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '830c991058e4'
down_revision = '647d7b9c0107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('is_open', sa.Boolean(), nullable=False, server_default='False'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'is_open')
    # ### end Alembic commands ###
