"""empty message

Revision ID: 87eb2e16dc88
Revises: 6873fbc7c624
Create Date: 2018-11-01 17:22:45.993736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87eb2e16dc88'
down_revision = '6873fbc7c624'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('creator_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'courses', 'professors', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'creator_id')
    # ### end Alembic commands ###
