"""empty message

Revision ID: 9dfee88017fa
Revises: 87eb2e16dc88
Create Date: 2018-11-01 17:51:13.566575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dfee88017fa'
down_revision = '87eb2e16dc88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses_profs',
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('professor_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'professor_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courses_profs')
    # ### end Alembic commands ###
