"""empty message

Revision ID: a22ca99c5c13
Revises: 2f6effab87b6
Create Date: 2018-11-02 17:38:10.777411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a22ca99c5c13'
down_revision = '2f6effab87b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('correct_answer', sa.String(length=1024), nullable=True))
    op.add_column('questions', sa.Column('number_of_options', sa.Integer(), nullable=False))
    op.add_column('questions', sa.Column('option1', sa.String(length=1024), nullable=True))
    op.add_column('questions', sa.Column('option2', sa.String(length=1024), nullable=True))
    op.add_column('questions', sa.Column('option3', sa.String(length=1024), nullable=True))
    op.add_column('questions', sa.Column('option4', sa.String(length=1024), nullable=True))
    op.add_column('questions', sa.Column('option5', sa.String(length=1024), nullable=True))
    op.add_column('questions', sa.Column('word_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'word_limit')
    op.drop_column('questions', 'option5')
    op.drop_column('questions', 'option4')
    op.drop_column('questions', 'option3')
    op.drop_column('questions', 'option2')
    op.drop_column('questions', 'option1')
    op.drop_column('questions', 'number_of_options')
    op.drop_column('questions', 'correct_answer')
    # ### end Alembic commands ###
