"""empty message

Revision ID: eb33a1389bba
Revises: 
Create Date: 2020-08-23 19:15:06.526137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb33a1389bba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('netId', sa.String(length=128), nullable=False),
    sa.Column('firstName', sa.String(length=128), nullable=True),
    sa.Column('lastName', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('netId')
    )
    op.create_table('students',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('netId', sa.String(length=128), nullable=False),
    sa.Column('firstName', sa.String(length=128), nullable=True),
    sa.Column('lastName', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('netId')
    )
    op.create_table('courses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dept', sa.String(length=128), nullable=True),
    sa.Column('coursenum', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('term', sa.String(length=32), nullable=True),
    sa.Column('creator_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('enroll_code', sa.String(length=8), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['professors.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses_profs',
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('professor_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id', 'professor_id')
    )
    op.create_table('courses_students',
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id', 'student_id')
    )
    op.create_table('lectures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('open_date', sa.Date(), nullable=True),
    sa.Column('close_date', sa.Date(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('scheduled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('creator_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creator_id'], ['professors.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lecture_id', sa.String(length=36), nullable=True),
    sa.Column('question_type', sa.String(length=32), nullable=False),
    sa.Column('question_title', sa.String(length=256), nullable=True),
    sa.Column('question_image', sa.String(length=10485760), nullable=True),
    sa.Column('question_text', sa.String(length=1024), nullable=True),
    sa.Column('correct_answer', sa.String(length=1024), nullable=True),
    sa.Column('creator_id', sa.String(length=36), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('option1', sa.String(length=1024), nullable=True),
    sa.Column('option2', sa.String(length=1024), nullable=True),
    sa.Column('option3', sa.String(length=1024), nullable=True),
    sa.Column('option4', sa.String(length=1024), nullable=True),
    sa.Column('option5', sa.String(length=1024), nullable=True),
    sa.Column('number_of_options', sa.Integer(), nullable=True),
    sa.Column('word_limit', sa.Integer(), nullable=True),
    sa.Column('lower_label', sa.String(length=32), nullable=True),
    sa.Column('upper_label', sa.String(length=32), nullable=True),
    sa.Column('question1', sa.String(length=1024), nullable=True),
    sa.Column('question2', sa.String(length=1024), nullable=True),
    sa.Column('question3', sa.String(length=1024), nullable=True),
    sa.Column('question4', sa.String(length=1024), nullable=True),
    sa.Column('question5', sa.String(length=1024), nullable=True),
    sa.Column('answer1', sa.String(length=1024), nullable=True),
    sa.Column('answer2', sa.String(length=1024), nullable=True),
    sa.Column('answer3', sa.String(length=1024), nullable=True),
    sa.Column('answer4', sa.String(length=1024), nullable=True),
    sa.Column('answer5', sa.String(length=1024), nullable=True),
    sa.Column('number_of_questions', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['professors.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lecture_id'], ['lectures.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=True),
    sa.Column('question_id', sa.String(length=36), nullable=True),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answers')
    op.drop_table('questions')
    op.drop_table('lectures')
    op.drop_table('courses_students')
    op.drop_table('courses_profs')
    op.drop_table('courses')
    op.drop_table('students')
    op.drop_table('professors')
    # ### end Alembic commands ###
