"""removed NOT NULL constraints for dept and coursenum

Revision ID: ec43371606e0
Revises: 356089557926
Create Date: 2018-11-29 08:24:59.687571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec43371606e0'
down_revision = '356089557926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'coursenum',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('courses', 'dept',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'dept',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('courses', 'coursenum',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
