"""empty message

Revision ID: 32264be76386
Revises: 1e9263812276
Create Date: 2018-11-11 16:36:44.579940

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '32264be76386'
down_revision = '1e9263812276'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answers')
    op.add_column('courses', sa.Column('enroll_code', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'enroll_code')
    op.create_table('answers',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('question_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name='answers_question_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='answers_student_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='answers_pkey')
    )
    # ### end Alembic commands ###
