"""added slider question model

Revision ID: 69cd3950245b
Revises: ec43371606e0
Create Date: 2018-12-15 17:28:41.830922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69cd3950245b'
down_revision = 'ec43371606e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('lower_label', sa.String(length=32), nullable=True))
    op.add_column('questions', sa.Column('upper_label', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'upper_label')
    op.drop_column('questions', 'lower_label')
    # ### end Alembic commands ###
