"""empty message

Revision ID: acd69d91761e
Revises: 611a81566c57
Create Date: 2020-08-24 18:04:11.509169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acd69d91761e'
down_revision = '611a81566c57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('is_current', sa.Boolean(), nullable=True))
    op.add_column('lectures', sa.Column('close_date', sa.Date(), nullable=True))
    op.add_column('lectures', sa.Column('open_date', sa.Date(), nullable=True))
    op.add_column('lectures', sa.Column('scheduled', sa.Boolean(), nullable=False))
    op.drop_column('lectures', 'enroll_code')
    op.add_column('questions', sa.Column('question_image', sa.String(length=10485760), nullable=True))
    op.drop_column('students', 'lecture_attending')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('lecture_attending', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('questions', 'question_image')
    op.add_column('lectures', sa.Column('enroll_code', sa.VARCHAR(length=8), autoincrement=False, nullable=True))
    op.drop_column('lectures', 'scheduled')
    op.drop_column('lectures', 'open_date')
    op.drop_column('lectures', 'close_date')
    op.drop_column('courses', 'is_current')
    # ### end Alembic commands ###
