"""empty message

Revision ID: b4e5eabc17f1
Revises: 611a81566c57
Create Date: 2020-08-23 16:23:01.617313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4e5eabc17f1'
down_revision = '611a81566c57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('professors', 'salt')
    op.drop_column('professors', 'password_hash')
    op.drop_column('students', 'lecture_attending')
    op.drop_column('students', 'salt')
    op.drop_column('students', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('password_hash', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('salt', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('lecture_attending', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('professors', sa.Column('password_hash', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.add_column('professors', sa.Column('salt', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
