"""empty message

Revision ID: b687a2b03143
Revises: 830c991058e4
Create Date: 2018-11-11 14:47:56.452016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b687a2b03143'
down_revision = '830c991058e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('enroll_code', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'enroll_code')
    # ### end Alembic commands ###
